# Generated by Django 5.1.4 on 2024-12-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_methods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
    ]
