# Generated by Django 5.1.4 on 2024-12-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_methods', '0002_alter_paymentmethod_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='expiry_date',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
