# Generated by Django 5.1.5 on 2025-02-04 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_address'),
        ('payment_methods', '0007_alter_accounts_payment_method_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accounts',
            new_name='Account',
        ),
    ]
