# Generated by Django 6.0 on 2026-01-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_methods', '0008_rename_accounts_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
