import type { Metadata } from "next";
import { raleway } from "@/app/ui/fonts";
import "./globals.css";
import "./ui/general.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${raleway.className} antialiased p4th-bg`}
      >
        {children}
      </body>
    </html>
  );
}
