# Generated by Django 5.1.5 on 2025-02-04 13:48

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_address'),
        ('transactions', '0002_alter_transaction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Transaction amount (must be positive)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance',
            field=models.DecimalField(decimal_places=2, help_text='Resulting balance after transaction', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when transaction was created'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(help_text='Description or notes about the transaction', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the transaction', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='recipient_id',
            field=models.ForeignKey(help_text='Recipient user for Send/Receive transactions', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='authentication.user'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failed', 'Failed')], default='Pending', help_text='Current status of the transaction', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('Send', 'Send Money'), ('Receive', 'Receive Money')], help_text='Type of transaction', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when transaction was last updated'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user_id',
            field=models.ForeignKey(help_text='User who initiated the transaction', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='authentication.user'),
        ),
    ]
