# Generated by Django 6.0 on 2026-01-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_amount_alter_transaction_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('Send', 'Send Money'), ('Receive', 'Receive Money'), ('Request', 'Money Request')], help_text='Type of transaction', max_length=10),
        ),
    ]
